// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjOBKNlngWW_FK9EGNKed_YM8Xc0lFLWs',
    appId: '1:176425288:web:b420cfb1f233adb1fe4b7d',
    messagingSenderId: '176425288',
    projectId: 'authenapp-6a863',
    authDomain: 'authenapp-6a863.firebaseapp.com',
    storageBucket: 'authenapp-6a863.firebasestorage.app',
    measurementId: 'G-YX3QTCG4X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfGgnArLVO9BTue0JPmET3pHxkB-ZDKDY',
    appId: '1:176425288:android:315170e3fb4ba020fe4b7d',
    messagingSenderId: '176425288',
    projectId: 'authenapp-6a863',
    storageBucket: 'authenapp-6a863.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcQkhf8GecQbhMHoi8bE0tpxcbL5Z3stQ',
    appId: '1:176425288:ios:3914f9c3d7d5eadbfe4b7d',
    messagingSenderId: '176425288',
    projectId: 'authenapp-6a863',
    storageBucket: 'authenapp-6a863.firebasestorage.app',
    iosClientId: '176425288-ec6hkii176lpgdlldursmrg6qol5shif.apps.googleusercontent.com',
    iosBundleId: 'com.example.planner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcQkhf8GecQbhMHoi8bE0tpxcbL5Z3stQ',
    appId: '1:176425288:ios:3914f9c3d7d5eadbfe4b7d',
    messagingSenderId: '176425288',
    projectId: 'authenapp-6a863',
    storageBucket: 'authenapp-6a863.firebasestorage.app',
    iosClientId: '176425288-ec6hkii176lpgdlldursmrg6qol5shif.apps.googleusercontent.com',
    iosBundleId: 'com.example.planner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjOBKNlngWW_FK9EGNKed_YM8Xc0lFLWs',
    appId: '1:176425288:web:c745e6f3682a35a5fe4b7d',
    messagingSenderId: '176425288',
    projectId: 'authenapp-6a863',
    authDomain: 'authenapp-6a863.firebaseapp.com',
    storageBucket: 'authenapp-6a863.firebasestorage.app',
    measurementId: 'G-DRVEQRRE3R',
  );
}
